new_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey.urls'))
]

survey/urls.py
from django.urls import path

app_name = 'survey'

from . import views
#import survey.api_views

urlpatterns = [

        # path('api/cities/', survey.api_views.CityList.as_view()),
         #path('api/cities/<int:id>/', survey.api_views.CityRetrieveUpdateDestroy.as_view()),

         path('', views.HomeView.as_view(), name='index'),
         path('states/', views.StateListView.as_view(), name="states"),

         path('cities/', views.CityView.as_view(), name="cities"),
         #path('states/<int:id/>', views.StateView.as_view(), name="state"),
         path('newcity/', views.NewCityView.as_view(), name="new_city"),
        # path('cities/<slug:pk>/update', views.UpdateCityView.as_view(), name="update_city"),

]

survey/models.py
from django.db import models

# Create your models here.
class State(models.Model):
    name = models.CharField(max_length=100)
    state_code  = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/states"

class City(models.Model):
    name = models.CharField(max_length=100)

    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    dist_code = models.IntegerField(default=0)
    population_total = models.IntegerField(default=0)
    population_male = models.IntegerField(default=0)
    population_female = models.IntegerField(default=0)
    population_child_total = models.IntegerField(default=0)
    population_child_male = models.IntegerField(default=0)
    population_child_female = models.IntegerField(default=0)
    literate_total = models.IntegerField(default=0)
    literate_male = models.IntegerField(default=0)
    literate_female = models.IntegerField(default=0)
    sex_ratio = models.IntegerField(default=0)
    child_sex_ratio = models.IntegerField(default=0)
    effective_literacy_rate_total = models.FloatField(default = 0.0)
    effective_literacy_rate_male = models.FloatField(default=0.0)
    effective_literacy_rate_female = models.FloatField(default=0.0)
    location = models.CharField(max_length=100, blank=True, null=True)
    total_graduates = models.IntegerField(default=0)
    male_graduates = models.IntegerField(default=0)
    female_graduates = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'cities'




    def __str__(self):
        return self.name



    def get_absolute_url(self):
        return "/cities"

survey/forms.py
from django import forms
from survey.models import *

class CreateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = '__all__'


class CreateStateForm(forms.ModelForm):
    class Meta:
        model = State
        fields = '__all__'

survey/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Count, F, Max, Sum


from .models import *
from .forms import *
# Create your views here.




class HomeView(TemplateView):
    template_name = 'survey/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cities'] = City.objects.all()
        context['states'] = State.objects.all()
        total_city_in_state = State.objects.annotate(cities = Count('city'))
        #total_states = State.objects.aggregate(sum=Sum('states'))
        #print(total_states)

        print(vars(State.objects.all()[0]))
        #print(total_city_in_state)
        #print(vars(total_city_in_state[0]))
        #print(total_city_in_state)
        #x = total_city_in_state[0]
        #print(x.cities)

        context['total_city_in_state'] = total_city_in_state


        return context


class CityView(ListView):
    template_name = 'survey/cities.html'
    model = City


def city(request, city_id):
    city = City.objects.get(id=city_id)
    return render(request, 'survey:city_detail.html', {'city': city})


class NewCityView(CreateView):
    model = City
    template_name = "survey/new_city.html"
    form_class = CreateCityForm

class UpdateCityView(UpdateView):
    template_name = "survey/update_city.html"
    model = City
    form_class = CreateCityForm


class StateListView(TemplateView):
    template_name = 'survey/states.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cities'] = City.objects.all()
        context['states'] = State.objects.all()
        total_city_in_state = State.objects.annotate(cities = Count('city'))
        context['total_city_in_state'] = total_city_in_state
        print(vars(total_city_in_state[0]))
        return context
"""total_city_in_state

def states(request):
    States = State.objects.all()
    cities = City.objects.all()
    total_city_in_state = State.objects.annotate(cities = Count('city'))
    context = {'states': states, 'cities': cities, 'total_city_in_state': total_city_in_state}
    x = total_city_in_state[0]
    print(x.cities)
    return render(request, 'survey/states.html', context)


def state(request, state_id):
    state = models.objects.get(id=state_id)
    cities = state.city_set.all()
    context = {'state': state, 'cities': cities}

    return render(request, 'survey/state.html', context)

"""

class StateView(DetailView):
    template_name = 'survey/state.html'
    model = State
    context_object_name = 'state'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        state = State.objects.get(id=id)
        print(var(state[0]))

        cities = state.city_set.all()
        context['state'] = state
        context['cities'] = cities


        return context






class NewStateView(CreateView):
    model = State
    template_name = "survey/new_state.html"
    form_class = CreateStateForm

class UpdateCityView(UpdateView):
    template_name = "survey/update_state.html"
    model = State
    form_class = CreateCityForm

survey/templates/survey/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

<body>
<p>
  <a href="{% url 'survey:index'%}">Home</a>
  <a href="{% url 'survey:cities'%}">Cities</a>
  <a href="{% url 'survey:states'%}">States</a>
  <a href="{% url 'survey:new_city'%}">Add new City</a>


</p>




</body>
{% block content %}  {% endblock content %}

survey/templates/survey/cities.html
{%  extends 'survey/base.html' %}
{% block content %}

<html>
<head>
  <title>City</title>
  <style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;
}
</style>
</head>
<body>
  <h2>City Survey</h2>
<p>Cities Information</p>
<a href="{% url 'survey:new_city' %} ">Add New City Info</a>

<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>state code</th>
    <th>state</th>
    <th>population_total</th>
    <th>population_male</th>
    <th>population_female</th>
    <th>population_child_total</th>
    <th>population_child_male</th>
    <th>population_child_female</th>
    <th>literate_total</th>
    <th>city.literate_male</th>
    <th>literate_female</th>
    <th>sex_ratio</th>
    <th>child_sex_ratio</th>
    <th>effective_literacy_rate_total</th>
    <th>effective_literacy_rate_male</th>
    <th>effective_literacy_rate_female</th>
    <th>location</th>
    <th>total_graduates</th>
    <th>male_graduates</th>
    <th>female_graduates</th>


  </tr>
  {% for city in object_list %}

  <tr>

    <td>
        {{ city.name }}
    </td>
    <td>{{city.state.state_code}}</td>
    <td>{{city.state.name}}</td>

    <td>{{city.population_total}}</td>
    <td>{{    city.population_male}}</td>
  <td>{{      city.population_female}}</td>
  <td>{{      city.population_child_total}}</td>
  <td>{{      city.population_child_male}}</td>
  <td>{{      city.population_child_female}}</td>
  <td>{{      city.literate_total}}</td>
  <td>{{      city.literate_male}}</td>
  <td>{{      city.literate_female}}</td>
  <td>{{      city.sex_ratio}}</td>
  <td>{{      city.child_sex_ratio}}</td>
  <td>{{      city.effective_literacy_rate_total}}</td>
  <td>{{      city.effective_literacy_rate_male}}</td>
  <td>{{      city.effective_literacy_rate_female}}</td>
  <td>{{      city.location }}</td>
  <td>{{      city.total_graduates }}</td>
  <td>{{      city.male_graduates }}</td>
  <td>{{      city.female_graduates}}</td>


  </tr>
  {% endfor  %}
</table>
{% endblock content %}

survey/templates/survey/city_detail.html
<html>
<head>
  <title>City</title>
  <style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;
}
</style>
</head>
<body>
  <h2>Ingredients</h2>
<p>Ingredient stock</p>


<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>state code</th>
    <th>state</th>


  </tr>


  <tr>

    <td>
        <a href="{% url "survey:update_city" city.id %}">{{ city.name }}</a>
    </td>
    <td>{{city.state_code}}</td>
    <td>{{city.state}}</td>


  </tr>
  {% endfor  %}
</table>

survey/templates/survey/index.html
{% extends 'survey/base.html' %}

{% block title %}City{% endblock %}
{% block content %}

<div class="home">
    <div>
        <h2>All States</h2>
        <table class="inventory-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>State Code</th>
                    <th>No of Cities</th>

                </tr>
            </thead>
            <tbody>
            {% for state in total_city_in_state %}
                <tr>
                    <td>{{ state.name }}</td>
                    <td>{{ state.state_code }}</td>
                    <td>{{state.cities}}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>



{% endblock content %}

survey/templates/survey/new_city.html
<h2>Add New City To survey</h2>
<form method="POST">
  <div>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit"/>
  </div>
</form>

survey/templates/survey/state.html
<div class="home">
    <div>
        <h2>{{state}}</h2>
        <table class="inventory-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>state</th>
                    <th>state_code</th>

                </tr>
            </thead>
            <tbody>
            {%  for city in state.cities.all %}
                <tr>
                    <td>{{ city.name }}</td>
                    <td>{{ city.state }}</td>
                    <td>{{city.state_code}}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

survey/templates/survey/states.html
{%  extends 'survey/base.html' %}

{%  block content %}
<div>
    <h2>State with cities</h2>
    <ul class="menu-items">
    {% for state in total_city_in_state %}
        <li>
            <div class="menu-item-header">
                <div class="menu-item-title">Name {{ state.name }}</div>
                <div class="menu-item-price">State Code {{ state.state_code}}</div>
                <div class="menu-item-price">Total No Of Cities{{ state.cities}}</div>
            </div>

            <ul class="menu-item-ingredients">

                {% for city in  state.city_set.all %}
                <li>{{ city.name }}</li>

                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock content %}

survey/templates/survey/update_city.html
<h2>Update City information</h2>
<form method="POST">
  <div>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit"/>
  </div>
</form>